modules/admin/controllers/BrigadesController.php
<?php

namespace app\modules\admin\controllers;

use app\models\Stations;
use Yii;
use app\models\Brigades;
use app\models\BrigadesSearch;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;

/**
 * BrigadesController implements the CRUD actions for Brigades model.
 */
class BrigadesController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => '\yii\filters\AccessControl',
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['personal_area']
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Brigades models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new BrigadesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Brigades model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        $user = Yii::$app->user;
        if(!$user->can('superadmin') && $user->identity->station_id !== $model->station_id) {
            throw new ForbiddenHttpException('Доступ к объектам других станций запрещён');
        }
        return $this->render('view', [
            'model' => $model,
        ]);
    }

    /**
     * Creates a new Brigades model.
     * If creation is successful, the browser will be redirected to the 'index' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Brigades();
        $user = Yii::$app->user;
        if (!$user->can('superadmin')) {
            $model->station_id = $user->identity->station_id;
        }

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            $query = Stations::find();
            if(!$user->can('superadmin')) {
                $query->where(['id' => $user->identity->station_id]);
            }
            return $this->render('create', [
                'model' => $model,
                'stations' => ArrayHelper::map($query->all(), 'id', 'name')
            ]);
        }
    }

    /**
     * Updates an existing Brigades model.
     * If update is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $user = Yii::$app->user;

        if(!$user->can('superadmin') && $user->identity->station_id !== $model->station_id) {
            throw new ForbiddenHttpException('Доступ к объектам других станций запрещён');
        }

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            $query = Stations::find();
            if(!$user->can('superadmin')) {
                $query->where(['id' => $user->identity->station_id]);
            }

            return $this->render('update', [
                'model' => $model,
                'stations' => ArrayHelper::map($query->all(), 'id', 'name')
            ]);
        }
    }

    /**
     * Deletes an existing Brigades model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Brigades model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Brigades the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Brigades::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * @return array
     */
    public function actionGetBrigades()
    {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $out = [];
        $parents = $_POST['depdrop_parents'];
        $station_id = $parents[0];
        if (isset($parents) && !empty($station_id)) {
            $array = ArrayHelper::toArray(Brigades::find()->where(['station_id' => $station_id])->all());
            foreach ($array as $value) {
                $out[] = ['id' => $value['id'], 'name' => $value['number']];
            }
            return ['output' => $out, 'selected' => $station_id];

        }
        return ['output' => '', 'selected' => ''];
    }
}

modules/admin/controllers/ChecklistsController.php
<?php

namespace app\modules\admin\controllers;

use app\models\Brigades;
use app\models\Customers;
use app\models\ExaminationTypes;
use app\models\Marks;
use app\models\Stations;
use app\models\WorkSubtypes;
use app\models\WorkTypes;
use Yii;
use app\models\Checklists;
use app\models\ChecklistsSearch;
use yii\data\ActiveDataProvider;
use yii\data\ArrayDataProvider;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\components\ChecklistsComponent;
use app\components\SessionComponent;

/**
 * ChecklistsController implements the CRUD actions for Checklists model.
 */
class ChecklistsController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => '\yii\filters\AccessControl',
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['personal_area']
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Checklists models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ChecklistsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'filterData' => $this->getFilterData()
        ]);
    }

    /**
     * Displays a single Checklists model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);

        $user = Yii::$app->user;

        $marks = Marks::find()->where(['checklist_id' => $id])->all();

        $marksIndexed = ArrayHelper::map(
            ArrayHelper::toArray($marks, [
                'app\models\Marks' => [
                    'workObjectName',
                    'criterionName',
                    'value'
                ],
            ]),
            'criterionName',
            'value',
            'workObjectName');

        if(!$user->can('superadmin') && $user->identity->station_id !== $model->station_id) {
            throw new ForbiddenHttpException('Доступ к объектам других станций запрещён');
        }

        return $this->render('view', [
            'model' => $model,
            'marks' => $marksIndexed,
        ]);
    }

    /**
     * Creates a new Checklists model.
     * If creation is successful, the browser will be redirected to the 'index' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = (new ChecklistsComponent())->getChecklist();

        $post = Yii::$app->request->post();
        $marks = $post['MarkCriteria'] ?? null;

        $transaction = Yii::$app->db->beginTransaction();

        if ($model->load($post) && $model->save() && !is_null($marks) && $model->saveMarks($marks)) {
            (new SessionComponent($model))->saveInfo();
            $transaction->commit();
            return $this->redirect(['index']);
        } else {
            $transaction->rollBack();
            if (!empty($post) && is_null($marks)) {
                Yii::$app->session->setFlash('empty_marks', 'Требуется выставить хотя бы одну оценку');
            }
            return $this->render('create', [
                'model' => $model,
                'filterData' => $this->getFilterData()
            ]);
        }
    }

    /**
     * Updates an existing Checklists model.
     * If update is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $post = Yii::$app->request->post();
        $marks = $post['MarkCriteria'] ?? null;
        $user = Yii::$app->user;

        if ($user->can('operator')) {
            throw new ForbiddenHttpException('Действие запрещено');
        }

        if(!$user->can('superadmin') && $user->identity->station_id !== $model->station_id) {
            throw new ForbiddenHttpException('Доступ к объектам других станций запрещён');
        }

        $transaction = Yii::$app->db->beginTransaction();

        if ($model->load($post) && $model->save() && !is_null($marks) && $model->saveMarks($marks, $model->id)) {
            $transaction->commit();
            return $this->redirect(['index']);
        } else {
            $transaction->rollBack();
            return $this->render('update', [
                'model' => $model,
                'filterData' => $this->getFilterData(),
                'marks' => $model->getMarkCriteriaWithMarks()
            ]);
        }
    }

    /**
     * Deletes an existing Checklists model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Checklists model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Checklists the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Checklists::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    private function getFilterData()
    {
        $brigadesQuery = Brigades::find();
        $stationsQuery = Stations::find();
        $user = Yii::$app->user;
        if(!$user->can('superadmin')) {
            $brigadesQuery->where(['station_id' => $user->identity->station_id]);
            $stationsQuery->where(['id' => $user->identity->station_id]);
        }
        return [
            'stations' => ArrayHelper::map($stationsQuery->all(), 'id', 'name'),
            'brigades' => ArrayHelper::map($brigadesQuery->all(), 'id', 'number'),
            'customers' => ArrayHelper::map(Customers::find()->all(), 'id', 'name'),
            'examinationTypes' => ArrayHelper::map(ExaminationTypes::find()->all(), 'id', 'name'),
            'workTypes' => ArrayHelper::map(WorkTypes::find()->all(), 'id', 'name'),
            'workSubTypes' => ArrayHelper::map(WorkSubTypes::find()->all(), 'id', 'name')
        ];
    }

    /**
     * @return \yii\web\Response
     */
    public function actionClear()
    {
        if(Yii::$app->request->isPost) {
            Yii::$app->session->set('info', '');
            return $this->redirect('/checklists/create');
        };
    }

}

modules/admin/views/checklists/create.php
<?php

use kartik\datecontrol\DateControl;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\widgets\DepDrop;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\Checklists */
/* @var $filterData array */

$this->title = 'Создание обходного листа';
$this->params['breadcrumbs'][] = ['label' => 'Обходные листы', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="checklists-create">
    <?= Html::a('Очистить основные данные', Url::to(['checklists/clear']), ['data-method' => 'POST', 'class' => 'text-danger']) ?>
    <?php $form = ActiveForm::begin(); ?>
    <div class="checklists-form box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">Основные данные</h3>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
            </div>
        </div>
        <div class="box-body">
            <div class="row">
                <div class="col-md-3"><?= $form->field($model, 'created_at')->widget('kartik\datecontrol\DateControl',
                        [
                            'type' => DateControl::FORMAT_DATE,
                            'widgetOptions' => [
                                'pluginOptions' => [
                                    'autoclose' => true
                                ]
                            ]
                        ]) ?>
                </div>
                <div class="col-md-3">

                    <?= $form->field($model, 'examination_type_id')->widget('\kartik\select2\Select2', [
                            'data' => $filterData['examinationTypes'],
                            'options' => ['placeholder' => 'Выберите ...'],
                            'pluginOptions' => [
                                'allowClear' => true
                            ]
                        ]
                    ) ?>

                </div>
                <div class="col-md-6">

                    <?= $form->field($model, 'customer_id')->widget('\kartik\select2\Select2', [
                            'data' => $filterData['customers'],
                            'options' => ['placeholder' => 'Выберите ...'],
                            'pluginOptions' => [
                                'allowClear' => true
                            ]
                        ]
                    ) ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3"><?= $form->field($model, 'station_id')->widget('\kartik\select2\Select2', [
                            'data' => $filterData['stations'],
                            'options' => ['placeholder' => 'Выберите дезстанцию ...'],
                            'pluginOptions' => [
                                'allowClear' => true
                            ],
                            'disabled' => !Yii::$app->user->can('superadmin')
                        ]
                    ); ?>
                </div>
                <?php if (Yii::$app->user->can('superadmin')): ?>
                    <div class="col-md-3"> <?= $form->field($model, 'brigade_id')->widget(DepDrop::class, [
                            'pluginOptions' => [
                                'depends' => ['checklists-station_id'],
                                'initialize' => true,
                                'placeholder' => 'Выбор бригады...',
                                'url' => Url::to(['/brigades/get-brigades'])
                            ],

                        ]) ?>
                    </div>
                <?php else: ?>
                    <div class="col-md-3"> <?= $form->field($model, 'brigade_id')->widget('\kartik\select2\Select2', [
                                'data' => $filterData['brigades'],
                                'options' => ['placeholder' => 'Выберите ...'],
                                'pluginOptions' => [
                                    'allowClear' => true
                                ]
                            ]
                        ) ?>
                    </div>
                <?php endif; ?>
                <div class="col-md-3"> <?= $form->field($model, 'work_type_id')->widget('\kartik\select2\Select2', [
                            'data' => $filterData['workTypes'],
                            'options' => ['placeholder' => 'Выберите ...'],
                            'pluginOptions' => [
                                'allowClear' => true
                            ]
                        ]
                    ) ?>
                </div>
                <div class="col-md-3">

                    <?= $form->field($model, 'work_subtype_id')->widget('\kartik\select2\Select2', [
                            'data' => $filterData['workSubTypes'],
                            'options' => ['placeholder' => 'Выберите ...'],
                            'pluginOptions' => [
                                'allowClear' => true
                            ]
                        ]
                    ) ?>
                </div>
            </div>
        </div>
    </div>
    <div class="checklists-form box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">Данные обходного листа</h3>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
            </div>
        </div>
        <div class="box-body">
            <div class="row">
                <div class="col-md-6"><?= $form->field($model, 'address_full')->widget('corpsepk\DaData\SuggestionsWidget',
                        [
                            'type' => 'ADDRESS',
                            'inputOptions' => [
                                'placeholder' => 'Введите адрес',
                                'onSelect' => null,
                            ]
                        ])
                    ?></div>
                <div class="col-md-3"><?= $form->field($model, 'index')->textInput() ?></div>
                <div class="col-md-3"> <?= $form->field($model, 'city')->textInput(['maxlength' => true]) ?></div>
            </div>
            <div class="row">
                <div class="col-md-4"><?= $form->field($model, 'district')->textInput(['maxlength' => true]) ?></div>
                <div class="col-md-4"><?= $form->field($model, 'region')->textInput(['maxlength' => true]) ?></div>
                <div class="col-md-4"><?= $form->field($model, 'street')->textInput(['maxlength' => true]) ?></div>
            </div>
            <div class="row">
                <div class="col-md-3"><?= $form->field($model, 'house')->textInput(['maxlength' => true]) ?></div>
                <div class="col-md-3"> <?= $form->field($model, 'flat')->textInput(['maxlength' => true]) ?></div>
                <div class="col-md-3"><?= $form->field($model, 'lat')->textInput() ?></div>
                <div class="col-md-3"> <?= $form->field($model, 'lon')->textInput() ?></div>
            </div>

        </div>

    </div>
    <div class="checklists-form box box-primary" id="checklist-marks" style="display: none">
        <div class="box-header with-border">
            <h3 class="box-title">Оценки</h3>
            <div class="box-alert"></div>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
            </div>
        </div>
        <div class="box-body">

        </div>

    </div>
    <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success
      btn-flat']) ?>

    <?= Html::a('Отменить', '/checklists/index',
        ['class' => 'btn
      btn-warning
      btn-flat']) ?>
    <?php ActiveForm::end(); ?>

    <?php $this->registerJsFile('/js/ddataChecklistForm.js', ['depends' => 'yii\web\JqueryAsset']) ?>
    <?php $this->registerJsFile('/js/checklistCreate.js', ['depends' => 'yii\web\JqueryAsset']) ?>

</div>

modules/admin/views/checklists/update.php
<?php

use kartik\datecontrol\DateControl;
use kartik\widgets\DepDrop;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\Checklists */
/* @var $filterData array */
/* @var $marks array */

$this->title = 'Редактирование Обходного листа: ' . Yii::$app->formatter->asDatetime($model->created_at);
$this->params['breadcrumbs'][] = ['label' => 'Обходные листы', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => Yii::$app->formatter->asDatetime($model->created_at), 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'редактирование';
?>
<div class="checklists-update">

    <?php $form = ActiveForm::begin(); ?>
    <div class="checklists-form box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">Основные данные</h3>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
            </div>
        </div>
        <div class="box-body">
            <div class="row">
                <div class="col-md-3"><?= $form->field($model, 'created_at')->widget('kartik\datecontrol\DateControl',
                        [
                            'type' => DateControl::FORMAT_DATE,
                            'widgetOptions' => [
                                'pluginOptions' => [
                                    'autoclose' => true
                                ]
                            ]
                        ]) ?>
                </div>
                <div class="col-md-3">

                    <?= $form->field($model, 'examination_type_id')->widget('\kartik\select2\Select2', [
                            'data' => $filterData['examinationTypes'],
                            'options' => ['placeholder' => 'Выберите ...'],
                            'pluginOptions' => [
                                'allowClear' => true
                            ]
                        ]
                    ) ?>

                </div>
                <div class="col-md-6">

                    <?= $form->field($model, 'customer_id')->widget('\kartik\select2\Select2', [
                            'data' => $filterData['customers'],
                            'options' => ['placeholder' => 'Выберите ...'],
                            'pluginOptions' => [
                                'allowClear' => true
                            ]
                        ]
                    ) ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3"><?= $form->field($model, 'station_id')->widget('\kartik\select2\Select2', [
                            'data' => $filterData['stations'],
                            'options' => ['placeholder' => 'Выберите дезстанцию ...'],
                            'pluginOptions' => [
                                'allowClear' => true
                            ],
                            'disabled' => !Yii::$app->user->can('superadmin')
                        ]
                    ); ?>
                </div>
                <?php if (Yii::$app->user->can('superadmin')): ?>
                    <div class="col-md-3"> <?= $form->field($model, 'brigade_id')->widget(DepDrop::class, [
                            'pluginOptions' => [
                                'depends' => ['checklists-station_id'],
                                'placeholder' => 'Выбор бригады...',
                                'url' => Url::to(['/brigades/get-brigades'])
                            ],

                        ]) ?>
                    </div>
                <?php else: ?>
                    <div class="col-md-3"> <?= $form->field($model, 'brigade_id')->widget('\kartik\select2\Select2', [
                                'data' => $filterData['brigades'],
                                'options' => ['placeholder' => 'Выберите ...'],
                                'pluginOptions' => [
                                    'allowClear' => true
                                ]
                            ]
                        ) ?>
                    </div>
                <?php endif; ?>
                <div class="col-md-3"> <?= $form->field($model, 'work_type_id')->widget('\kartik\select2\Select2', [
                            'data' => $filterData['workTypes'],
                            'options' => ['placeholder' => 'Выберите ...'],
                            'pluginOptions' => [
                                'allowClear' => true
                            ]
                        ]
                    ) ?>
                </div>
                <div class="col-md-3">

                    <?= $form->field($model, 'work_subtype_id')->widget('\kartik\select2\Select2', [
                            'data' => $filterData['workSubTypes'],
                            'options' => ['placeholder' => 'Выберите ...'],
                            'pluginOptions' => [
                                'allowClear' => true
                            ]
                        ]
                    ) ?>
                </div>
            </div>
        </div>
    </div>
    <div class="checklists-form box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">Данные обходного листа</h3>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
            </div>
        </div>
        <div class="box-body">
            <div class="row">
                <div class="col-md-6"><?= $form->field($model, 'address_full')->widget('corpsepk\DaData\SuggestionsWidget',
                        [
                            'type' => 'ADDRESS',
                            'inputOptions' => [
                                'placeholder' => 'Введите адрес',
                                'onSelect' => null,
                            ]
                        ])
                    ?></div>
                <div class="col-md-3"><?= $form->field($model, 'index')->textInput() ?></div>
                <div class="col-md-3"> <?= $form->field($model, 'city')->textInput(['maxlength' => true]) ?></div>
            </div>
            <div class="row">
                <div class="col-md-4"><?= $form->field($model, 'district')->textInput(['maxlength' => true]) ?></div>
                <div class="col-md-4"><?= $form->field($model, 'region')->textInput(['maxlength' => true]) ?></div>
                <div class="col-md-4"><?= $form->field($model, 'street')->textInput(['maxlength' => true]) ?></div>
            </div>
            <div class="row">
                <div class="col-md-3"><?= $form->field($model, 'house')->textInput(['maxlength' => true]) ?></div>
                <div class="col-md-3"> <?= $form->field($model, 'flat')->textInput(['maxlength' => true]) ?></div>
                <div class="col-md-3"><?= $form->field($model, 'lat')->textInput() ?></div>
                <div class="col-md-3"> <?= $form->field($model, 'lon')->textInput() ?></div>
            </div>

        </div>

    </div>
    <div class="checklists-form box box-primary" id="checklist-marks">
        <div class="box-header with-border">
            <h3 class="box-title">Оценки</h3>
            <div class="box-alert"></div>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
            </div>
        </div>
        <div class="box-body">
            <?php foreach ($marks as $mark): ?>
                <h4 class="box-title"><?= $mark['name'] ?></h4>

                <div class="row">
                    <?php foreach ($mark['criteria'] as $value): ?>
                        <div class="form-group col-md-4">
                            <label><?= $value['name'] ?></label>
                            <div class="form_radio_btn" tabindex="0">
                                <input id="mark_criteria_<?= $value['id'] ?>_0" type="radio"
                                       name="MarkCriteria[<?= $value['id'] ?>]" value="0"
                                       <?php if ($value['mark'] === 0): ?>checked<?php endif; ?>>
                                <label for="mark_criteria_<?= $value['id'] ?>_0">0</label>
                            </div>
                            <div class="form_radio_btn" tabindex="0">
                                <input id="mark_criteria_<?= $value['id'] ?>_1" type="radio"
                                       name="MarkCriteria[<?= $value['id'] ?>]" value="1"
                                       <?php if ($value['mark'] === 1): ?>checked<?php endif; ?>>
                                <label for="mark_criteria_<?= $value['id'] ?>_1">1</label>
                            </div>
                            <div class="form_radio_btn" tabindex="0">
                                <input id="mark_criteria_<?= $value['id'] ?>_2" type="radio"
                                       name="MarkCriteria[<?= $value['id'] ?>]" value="2"
                                       <?php if ($value['mark'] === 2): ?>checked<?php endif; ?>>
                                <label for="mark_criteria_<?= $value['id'] ?>_2">2</label>
                            </div>
                            <div class="form_radio_btn" tabindex="0">
                                <input id="mark_criteria_<?= $value['id'] ?>_3" type="radio"
                                       name="MarkCriteria[<?= $value['id'] ?>]" value="3"
                                       <?php if ($value['mark'] === 3): ?>checked<?php endif; ?>>
                                <label for="mark_criteria_<?= $value['id'] ?>_3">3</label>
                            </div>
                            <div class="form_radio_btn" tabindex="0">
                                <input id="mark_criteria_<?= $value['id'] ?>_4" type="radio"
                                       name="MarkCriteria[<?= $value['id'] ?>]" value="4"
                                       <?php if ($value['mark'] === 4): ?>checked<?php endif; ?>>
                                <label for="mark_criteria_<?= $value['id'] ?>_4">4</label>
                            </div>
                        </div>

                    <?php endforeach; ?>
                </div>
            <?php endforeach; ?>
        </div>

    </div>
    <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success
      btn-flat']) ?>

    <?= Html::a('Отменить', '/checklists/index',
        ['class' => 'btn
      btn-warning
      btn-flat']) ?>
    <?php ActiveForm::end(); ?>

    <?php $this->registerJsFile('/js/ddataChecklistForm.js', ['depends' => 'yii\web\JqueryAsset']) ?>
    <?php $this->registerJsFile('/js/checklistUpdate.js', ['depends' => 'yii\web\JqueryAsset']) ?>

</div>