modules/admin/controllers/UserController.php
<?php

namespace app\modules\admin\controllers;

use app\models\AuthItem;
use app\models\Stations;
use app\models\UserCreate;
use Yii;
use app\models\User;
use app\models\UserSearch;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
  /**
   * @inheritdoc
   */
  public function behaviors()
  {
    return [
      'verbs' => [
        'class' => VerbFilter::className(),
        'actions' => [
          'delete' => ['POST'],
        ],
      ],
      'access' => [
        'class' => '\yii\filters\AccessControl',
        'rules' => [
          [
            'allow' => true,
            'roles' => ['superadmin']
          ],
        ],
      ],
    ];
  }

  /**
   * Lists all User models.
   * @return mixed
   */
  public function actionIndex()
  {
    $searchModel = new UserSearch();
    $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
    $stations[0] = 'Не задана';
    $stations = $stations + ArrayHelper::map(Stations::find()->all(), 'id', 'name');

    return $this->render('index', [
      'searchModel' => $searchModel,
      'dataProvider' => $dataProvider,
      'roles' => ArrayHelper::map(
        AuthItem::find()->where(['type' => 1])->all(),
        'name', 'description'
      ),
      'stations' => $stations
    ]);
  }

  /**
   * Displays a single User model.
   * @param integer $id
   * @return mixed
   */
  public function actionView($id)
  {
    return $this->render('view', [
      'model' => $this->findModel($id),
    ]);
  }

  /**
   * Creates a new User model.
   * If creation is successful, the browser will be redirected to the 'index' page.
   * @return mixed
   */
  public function actionCreate()
  {
    $model = new UserCreate();
    $post = Yii::$app->request->post();
    $stations = ArrayHelper::map(Stations::find()->all(), 'id', 'name');
    $roles = ArrayHelper::map(
      AuthItem::find()->where(['type' => 1])->all(),
      'name', 'description'
    );

    if ($model->load($post) && $model->create()) {
      return $this->redirect(['index']);
    } else {
      return $this->render('create', [
        'model' => $model,
        'stations' => $stations,
        'roles' => $roles
      ]);
    }
  }

  /**
   * Updates an existing User model.
   * If update is successful, the browser will be redirected to the 'index' page.
   * @param integer $id
   * @return mixed
   */
  public function actionUpdate($id)
  {
    $model = $this->findModel($id);
    $stations = ArrayHelper::map(Stations::find()->all(), 'id', 'name');
    $roles = ArrayHelper::map(
      AuthItem::find()->where(['type' => 1])->all(),
      'name', 'description'
    );

    if ($model->load(Yii::$app->request->post()) && $model->save()) {
      return $this->redirect(['index']);
    } else {
      return $this->render('update', [
        'stations' => $stations,
        'roles' => $roles,
        'model' => $model,
      ]);
    }
  }

  /**
   * Deletes an existing User model.
   * If deletion is successful, the browser will be redirected to the 'index' page.
   * @param integer $id
   * @return mixed
   */
  public function actionDelete($id)
  {
    $this->findModel($id)->delete();

    return $this->redirect(['index']);
  }


  /**
   * Finds the User model based on its primary key value.
   * If the model is not found, a 404 HTTP exception will be thrown.
   * @param integer $id
   * @return User the loaded model
   * @throws NotFoundHttpException if the model cannot be found
   */
  protected function findModel($id)
  {
    if (($model = User::findOne($id)) !== null) {
      return $model;
    } else {
      throw new NotFoundHttpException('The requested page does not exist.');
    }
  }

  public function actionChangePassword($id)
  {
    $model = $this->findModel($id);
    $post = Yii::$app->request->post();
    if (isset($post['password']) && $model->setPassword($post['password']) && $model->save()) {
      return $this->redirect(['view', 'id' => $model->id]);
    } else {
      return $this->render('change-password', [
        'model' => $model,
      ]);
    }
  }

}

modules/admin/views/user/change-password.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;


/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = 'Смена пароля пользователя: ' . $model->email;
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->email, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'смена пароля';
?>
<div class="users-change-password">

  <div class="users-form box box-primary">
      <?php $form = ActiveForm::begin(); ?>
    <div class="box-body table-responsive">

        <?= Html::passwordInput('password', '', [
            'class' => 'form-control'
        ])?>

    </div>
    <div class="box-footer">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success btn-flat']) ?>
    </div>
      <?php ActiveForm::end(); ?>
  </div>

</div>

modules/admin/views/user/create.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\widgets\Select2;


/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $stations array */
/* @var $roles array */

$this->title = 'Создание пользователя';
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="users-create">
  <style>
    .select2-container--krajee .select2-selection {
      border-radius: unset!important;
    }
  </style>
  <div class="users-form box box-primary">
    <?php $form = ActiveForm::begin(); ?>
    
    <div class="box-body table-responsive">
      
      <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

      <?= $form->field($model, 'password')->passwordInput(['maxlength' => true]) ?>

      <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

      <?= $form->field($model, 'surname')->textInput(['maxlength' => true]) ?>

      <?= $form->field($model, 'patronymic')->textInput(['maxlength' => true]) ?>

      <?= $form->field($model, 'phone')->textInput(['maxlength' => true]) ?>

      <?= $form->field($model, 'role')->dropDownList($roles, [
        'class' => 'form-control user-role-input'
      ]) ?>

      <?= $form->field($model, 'station_id')->widget(Select2::classname(), [
        'data' => $stations,
        'options' => ['placeholder' => 'Выберите дезстанцию ...', 'class' => 'user-object-input'],
        'pluginOptions' => [
          'allowClear' => true
        ],
      ]);
      ?>

    </div>
    <div class="box-footer">
      <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success btn-flat']) ?>
      <?= Html::a('Отменить', '/user/index',
        ['class' => 'btn
      btn-warning
      btn-flat']) ?>
    </div>
    <?php ActiveForm::end(); ?>
  </div>
</div>

<?php $this->registerJsFile('/js/userObject.js', ['depends' => 'yii\web\JqueryAsset'])?>

modules/admin/views/user/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use app\models\User;
use app\models\Stations;

/* @var $this yii\web\View */
/* @var $searchModel app\models\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $roles array */
/* @var $stations array */

$this->title = 'Пользователи';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-index box box-primary">
  <div class="box-header with-border">
    <?= Html::a('Добавить Пользователя', ['create'], ['class' => 'btn btn-success btn-flat']) ?>
  </div>
  <div class="box-body table-responsive no-padding">
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
    <?= GridView::widget([
      'dataProvider' => $dataProvider,
      'filterModel' => $searchModel,
      'layout' => "{items}\n{summary}\n{pager}",
      'columns' => [
        'id',
        'email:email',
        'name',
        'surname',
        'patronymic',
        'phone',
        [
          'attribute' => 'station_id',
          'filter' => $stations,
          'value' => function(User $model) {return $model->stationName;}
        ],
        [
          'attribute' => 'role',
          'value' => function (User $model) {
            return $model->getRoleDescription();
          },
          'filter' => $roles
        ],
        [
          'attribute' => 'active',
          'label' => 'Активен',
          'filter' => [
            0 => 'Нет',
            1 => 'Да',
          ],
          'value' => function (User $model) {
            return $model->active
              ? '<span class="glyphicon glyphicon-ok" aria-hidden="true"></span>'
              : '<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>';
          },
          'format' => 'raw'
        ],
        [
          'class' => 'yii\grid\ActionColumn',
          'template' => '{view} {update} {delete} {change-password}',
          'buttons' => [
            'change-password' => function ($url) {
              return Html::a(
                '<span class="glyphicon glyphicon-lock" aria-hidden="true"></span>',
                $url,
                ['title' => 'Сменить пароль']
              );
            }
          ]
        ],
      ],
    ]); ?>
  </div>
</div>

modules/admin/views/user/update.php
<?php

use kartik\widgets\Select2;
use kartik\widgets\SwitchInput;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $stations array */
/* @var $roles array */


$this->title = 'Редактирование пользователя: ' . $model->email;
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->email, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'редактирование';
?>
<div class="user-update">

  <style>
    .select2-container--krajee .select2-selection {
      border-radius: unset !important;
    }
  </style>

  <div class="users-form box box-primary">

    <?php $form = ActiveForm::begin(); ?>

    <div class="box-body table-responsive">

      <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

      <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

      <?= $form->field($model, 'surname')->textInput(['maxlength' => true]) ?>

      <?= $form->field($model, 'patronymic')->textInput(['maxlength' => true]) ?>

      <?= $form->field($model, 'phone')->textInput(['maxlength' => true]) ?>

      <?= $form->field($model, 'role')->dropDownList($roles, [
        'class' => 'form-control user-role-input'
      ]) ?>

      <?= $form->field($model, 'station_id')->widget(Select2::classname(), [
        'data' => $stations,
        'options' => ['prompt' => 'Выберите дезстанцию ...', 'class' => 'user-object-input'],
        'pluginOptions' => [
          'allowClear' => true
        ],
      ]);
      ?>

      <?= $form->field($model, 'active')->widget(SwitchInput::className(), [
        'pluginOptions' => [
          'onText' => '<i class="glyphicon glyphicon-ok"></i>',
          'offText' => '<i class="glyphicon glyphicon-remove"></i>',
        ]
      ]) ?>

    </div>
    <div class="box-footer">
      <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success btn-flat']) ?>
      <?= Html::a('Отменить', '/user/index',
        ['class' => 'btn
      btn-warning
      btn-flat']) ?>
    </div>

    <?php ActiveForm::end(); ?>
  </div>

</div>

<?php $this->registerJsFile('/js/userObject.js', ['depends' => 'yii\web\JqueryAsset']) ?>

modules/admin/views/user/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = $model->email;
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="user-view box box-primary">
  <div class="box-header">
    <?= Html::a('Редактировать', ['update', 'id' => $model->id], ['class'
    => 'btn btn-primary btn-flat']) ?>
    <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
      'class' => 'btn btn-danger btn-flat',
      'data' => [
        'confirm' => 'Вы действительно хотите удалить?',
        'method' => 'post',
      ],
    ]) ?>
  </div>
  <div class="box-body table-responsive no-padding">
    <?= DetailView::widget([
      'model' => $model,
      'attributes' => [
        'id',
        'email:email',
        'auth_key',
        'name',
        'surname',
        'patronymic',
        'phone',
        'roleDescription',
        'active',
        [
          'attribute' => 'created_at',
          'value' => function (\app\models\User $model) {
            return Yii::$app->formatter->asDatetime($model->created_at, 'php:d.m.Y H:i:s');
          },
          'format' => 'raw'
        ],
        [
          'attribute' => 'updated_at',
          'value' => function (\app\models\User $model) {
            return Yii::$app->formatter->asDatetime($model->updated_at, 'php:d.m.Y H:i:s');
          },
          'format' => 'raw'
        ],
        'station_id',
      ],
    ]) ?>
  </div>
</div>