modules/admin/controllers/MarkCriteriaController.php
<?php

namespace app\modules\admin\controllers;

use app\models\WorkObjects;
use Yii;
use app\models\MarkCriteria;
use app\models\MarkCriteriaSearch;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * MarkCriteriaController implements the CRUD actions for MarkCriteria model.
 */
class MarkCriteriaController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => '\yii\filters\AccessControl',
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['superadmin']
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all MarkCriteria models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new MarkCriteriaSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single MarkCriteria model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new MarkCriteria model.
     * If creation is successful, the browser will be redirected to the 'index' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new MarkCriteria();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                'model' => $model,
                'objects' => $this->getFilterData()
            ]);
        }
    }

    /**
     * Updates an existing MarkCriteria model.
     * If update is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                'model' => $model,
                'objects' => $this->getFilterData()
            ]);
        }
    }

    /**
     * Deletes an existing MarkCriteria model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the MarkCriteria model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return MarkCriteria the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = MarkCriteria::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * @return array
     */
    private function getFilterData()
    {
        $models = WorkObjects::find()->all();
        $array = ArrayHelper::toArray($models, [
            WorkObjects::class => [
                'id',
                'name' => function (WorkObjects $model) {
                    return "{$model->name} ({$model->examinationTypeName}, {$model->workTypeName}, {$model->workSubtypeName})";
                }
            ]
        ]);

        return ArrayHelper::map($array, 'id', 'name');
    }
}

modules/admin/views/mark-criteria/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\widgets\Select2;

/* @var $this yii\web\View */
/* @var $model app\models\MarkCriteria */
/* @var $form yii\widgets\ActiveForm */
/* @var $objects array */
?>

<div class="mark-criteria-form box box-primary">
    <?php $form = ActiveForm::begin(); ?>
    <div class="box-body table-responsive">

        <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'work_object_id')->widget('\kartik\select2\Select2', [
                'data' => $objects,
                'options' => ['placeholder' => 'Выберите...'],
                'pluginOptions' => [
                    'allowClear' => true
                ]
            ]
        )?>

    </div>
    <div class="box-footer">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success
      btn-flat']) ?>
      <?= Html::a('Отменить', '/mark-criteria/index',
      ['class' => 'btn
      btn-warning
      btn-flat']) ?>

    </div>
    <?php ActiveForm::end(); ?>
</div>

modules/admin/views/mark-criteria/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\MarkCriteria */
/* @var $objects array */

$this->title = 'Создание критерия';
$this->params['breadcrumbs'][] = ['label' => 'Критерии оценки', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="mark-criteria-create">

    <?= $this->render('_form', [
        'model' => $model,
        'objects' => $objects

    ]) ?>

</div>

modules/admin/views/mark-criteria/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\MarkCriteriaSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Критерии оценки';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="mark-criteria-index box box-primary">
    <div class="box-header with-border">
        <?= Html::a('Добавить критерий', ['create'], ['class' => 'btn btn-success btn-flat']) ?>
    </div>
    <div class="box-body table-responsive no-padding">
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'layout' => "{items}\n{summary}\n{pager}",
            'columns' => [
                'name',
                'workObjectName',
                'examinationTypeName',
                'workTypeName',
                'workSubTypeName',

                ['class' => 'yii\grid\ActionColumn'],
            ],
        ]); ?>
    </div>
</div>

modules/admin/views/mark-criteria/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\MarkCriteria */
/* @var $objects array */

$this->title = 'Редактирование критерия: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Критерии оценки', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'редактирование';
?>
<div class="mark-criteria-update">

    <?= $this->render('_form', [
        'model' => $model,
        'objects' => $objects
    ]) ?>

</div>

modules/admin/views/mark-criteria/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\MarkCriteria */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Критерии оценки', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="mark-criteria-view box box-primary">
    <div class="box-header">
        <?= Html::a('Редактировать', ['update', 'id' => $model->id], ['class'
      => 'btn btn-primary btn-flat']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger btn-flat',
            'data' => [
                'confirm' => 'Вы действительно хотите удалить?',
                'method' => 'post',
            ],
        ]) ?>
    </div>
    <div class="box-body table-responsive no-padding">
        <?= DetailView::widget([
            'model' => $model,
            'attributes' => [
//                'id',
                'name',
                'workObjectName',
                'examinationTypeName',
                'workTypeName',
                'workSubTypeName',
            ],
        ]) ?>
    </div>
</div>